version: '3'
services:
  nginx:
    build:
      context: ./nginx        # Diretório onde está o Dockerfile
      dockerfile: Dockerfile  # Nome do Dockerfile
    ports:
      - "443:443"             # Mapeia a porta 443 do container para a porta 443 do host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./wordpress:/var/www/html
      #- ./nginx.conf:/etc/nginx/nginx.conf  # Monta o arquivo nginx.conf no container
      #- ./ssl:/etc/nginx/ssl  # Monta a pasta ssl para certificados, se necessário
    restart: always           # Reinicia o container automaticamente em caso de falhas
    depends_on:
      - wordpress
  
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    expose:
      - "9000"
    restart: always
    depends_on:
      - db


  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysqld
    restart: always

volumes:
  db_data: