# Usa penultima versão do estavel do wordpress
FROM alpine:3.18

# Instala dependências básicas e PHP-FPM com extensões necessárias para o WordPress
RUN apk update && \
    apk add --no-cache php81 php81-fpm php81-mysqli php81-pdo php81-pdo_mysql php81-opcache php81-phar php81-json curl

# Configura PHP-FPM
RUN mkdir -p /run/php && \
    sed -i 's|listen = 127.0.0.1:9000|listen = 9000|' /etc/php81/php-fpm.d/www.conf

# Baixa e configura WordPress
WORKDIR /var/www/html
RUN curl -O https://wordpress.org/latest.tar.gz && \
    tar -xzf latest.tar.gz --strip-components=1 && \
    rm latest.tar.gz

# Configura permissões para usuario padrao do alpine
RUN chown -R nobody:nobody /var/www/html

# Expoe porta 9000 para conexão com PHP-FPM
EXPOSE 9000

# Iniciar o PHP-FPM
CMD ["php-fpm81", "-F"]
